### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [theodorusclarence/theodorusclarence.com#348]
![image](https://user-images.githubusercontent.com/93640141/214285886-365ed19f-412a-47cc-8ac6-adf0a6a4baf7.png)

I was trying to implement this and did it successfully. 
> diffrent color for the border what ever I need

```tsx
import * as React from 'react';

export default function CustomBlockQuote(
  props: React.ComponentPropsWithRef<'blockquote'>
) {
  const content = (props.children as Array<React.ReactElement>)[1]?.props
    .children;
  const data = content.split('---');
  if ((content as string).includes('---'))
    return <blockquote className={`color-${data[0]}`}>{data[1]}</blockquote>;
  return <blockquote>{content}</blockquote>;
}
```

```mdx
## Introduction

> Using Rem and Em units is better than using px.

> red---hey there
```

```css
.prose blockquote.color-red {
  border-image: linear-gradient(to top, #ff0062, #f35900, #fdcf00) 1;
}
```

Is this good way to do or you suggest something else.?
